### PR TITLE
A few packaging-related fixes.

### PR DESCRIPTION
**Pull request by leamas**
Some renaming to be more inline with other plugins, Makefile fixes (notably DESTDIR) support, whitespace, line endings and such.

This is an update of my previous request.

EDIT: Updating linker paths + some comments

### CODE REVIEW

**Comment by jdunn14** [comment]
Since this driver merged back into our main repository should I assume this pull is junk now?

**Comment by leamas** [comment]
> Since this driver merged back into our main repository should I assume this pull is junk now?

Yes. 
Now when it's merged , we should just leave a pointer to the main repo here

**Comment by jdunn14** [comment]
Alright, stupid GitHub Q: what's the best way to leave a pointer back?  If nothing else I can basically nuke all the code and just leave the README w a little text....  Better approach?

**Comment by leamas** [comment]
Yes,  nuking the code , leaving/updating README is the way. I think...

**Comment by jdunn14** [comment]
Done, all future work should be over in that main repo.  Closing this pull request.

**Pull request closed without merging**
